### ISSUE TITLE
Apply Spring 4 & IO Platform

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw-web-multi-blank#38]
see terasolunaorg/terasoluna-gfw#132 & terasolunaorg/terasoluna-gfw#178.

- [x] Modify pom files. #45
- [x] Modify to use class of tiles3. #45
- [x] Modify to use dtd of tiles3. #45
- [x] Add sql comment in H2-schema.sql because occur the error when file content are empty. #45 
- [x] Add tiles-extras(jsp tag library) in include.jsp #45
- [x] Modify as manage scope of libraries by parent project. #45 
- [x] Apply Commons-dbcp2. #45 
- [x] Add el-api for test. Feedback from guideline of Validation(detail see [here](https://github.com/terasolunaorg/guideline/pull/603/files)) #64 
- [x] Apply namespace of ViewResolver #69
